services:
  proxy:
    environment:
      ARP_MASTER_KEY_FILE: /run/secrets/master_key_secret
    secrets:
      - master_key_secret

secrets:
  master_key_secret:
    file: ./secrets/master_key_secret
